# LumiCore configuration (PlaceholderAPI supported)

# Totem Message
# This message will be used if a player uses a custom model data totem that is not on the list or is a vanilla totem
totem-message: '&6&lLumiCore &8&l>> &7The player %player% &7has consumed a &6Immortality Totem &7Cause: %causa%'

# Custom Model Data Totems
custom-model-totems:
  1:
    message: '&6&lLumiCore &8&l>> &7The player %player% &7has consumed a &6Immortality Totem Custom Model Data 1 &7Cause: %causa%'
  2:
    message: '&6&lLumiCore &8&l>> &7The player %player% &7has consumed a &6LOL Totem Custom Model Data 2 &7Cause: %causa%'

# Causes of the Totem
messages:
  FALL: 'Fall'
  FIRE: 'Fire'
  LAVA: 'Lava'
  DROWNING: 'Drowning'
  DRAGON_BREATH: 'Dragon Breath'
  SONIC_BOOM: 'Warden Sonic Attack'
  PLAYER: 'Player'
  WITHER: 'Wither Effect'
  WORLD_BORDER: 'World Border'
  SUFFOCATION: 'Suffocation'
  STARVATION: 'Starvation'
  LIGHTNING: 'Lightning'
  PRIMED_TNT: 'Explosion'
  BLOCK_EXPLOSION: 'Explosion'
  FIREBALL: 'Fireball'
  MAGIC: 'Magic'
  POISON: 'Poison'
  ENDER_PEARL: 'Ender Pearl Damage'
  UNKNOWN: 'Custom'
  CUSTOM: 'Custom'

# Tomb message on the poster
line-1: '&7&lR.I.P'
line-2: '%player%'
line-3: '%date%'
line-4: '&0....'

# Messages when entering and leaving the server
join-message: '&a%player% joined the server'
leave-message: '&7%player% left the server'

# Death message in action_bar and time of the actiobar_bar
chat-actionbar-death: '&b&l%death_cause%'
chat-actionbar-time: 1

# Generate grave upon death
generate-grave: true

# Personalized death, spectator and message of the actionbar
custom-death: true

# Send messages to chat when someone consumes a totem
totem-use: true

# These are the custom input and output messages to the server, if you want to use the default Minecraft messages, set this to "false"
custom-join-and-leave: true