name: LumiCore
version: '1.0.2'
main: main.lumicore.LumiCore
author: Luminary Minecraft Studio
website: https://discord.luminarystudio.xyz
api-version: '1.17'
authors: [GekoXD]
description: LumiCore is a highly configurable plugin that adds tombstones upon death, custom messages
commands:
  lc:
    description: Index Main Command
    usage: Incomplete command please enter the complete command. /lc <subcomando>
    permission: luminarycore.admin
    aliases:
      - lc
