name: LumiCore
version: '1.0.3'
main: main.lumicore.LumiCore
author: GekoXD
website: https://discord.luminarystudio.xyz
api-version: '1.17'
softdepend: [PlaceholderAPI]
description: LumiCore is a highly configurable plugin that adds tombstones upon death, custom messages
commands:
  lc:
    description: Index Main Command
    usage: Incomplete command please enter the complete command. /lc <subcomando>
    permission: luminarycore.admin
    aliases:
      - lc
